version: "3.7"
services:

  mongo:
    image: mongo:3.6.17
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

#  redis:
#    image: redis:6.0.9
#    container_name: redis
#    ports:
#      - 6379:6379
#    command: redis-server --requirepass ${REDIS_RATELIMIT_PASSWORD}

volumes:
  mongodb: {}
